# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tend

  pod 'Firebase/Analytics'
  pod 'FirebaseUI'
  pod 'Firebase/Storage'

end
